version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/nginx/ssl
    restart: always
    networks:
      - portfolio_network

  server:
    build:
      context: ./server
    ports:
      - "8888:8888" 
    depends_on:
      - mongo
    env_file:
      - ./server/.docker.env
    networks:
      - portfolio_network
      
  mongo:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    volumes:
      - mongo-data:/data/db  
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  mongo-data:
